DROP VIEW IF EXISTS towar_zysk;
DROP TABLE IF EXISTS kod_kreskowy;
DROP TABLE IF EXISTS pozycja;
DROP TABLE IF EXISTS zapas;
DROP TABLE IF EXISTS zamowienie;
DROP TABLE IF EXISTS towar;
DROP TABLE IF EXISTS klient;